import { lazy } from 'react'

export const LoginPage = lazy(() => import('@/features/auth/pages/login-page').then(({ LoginPage }) => ({ default: LoginPage })))
export const RegisterPage = lazy(() => import('@/features/auth/pages/register-page').then(({ RegisterPage }) => ({ default: RegisterPage })))
export const EmailConfirmationPage = lazy(() => import('@/features/auth/pages/email-confirmation-page').then(({ EmailConfirmationPage }) => ({ default: EmailConfirmationPage })))
export const DashboardPage = lazy(() => import('@/features/dashboard/pages/dashboard-page').then(({ DashboardPage }) => ({ default: DashboardPage })))
export const IdeasPage = lazy(() => import('@/features/ideas/pages/ideas-page').then(({ IdeasPage }) => ({ default: IdeasPage })))
export const MarketMapPage = lazy(() => import('@/features/market-map/pages/market-map-page').then(({ MarketMapPage }) => ({ default: MarketMapPage })))
export const PillarsPage = lazy(() => import('@/features/pillars/pages/pillars-page').then(({ PillarsPage }) => ({ default: PillarsPage })))
export const ScriptsPage = lazy(() => import('@/features/scripts/pages/scripts-page').then(({ ScriptsPage }) => ({ default: ScriptsPage })))
export const ScriptPreviewPage = lazy(() => import('@/features/scripts/pages/script-preview-page').then(({ ScriptPreviewPage }) => ({ default: ScriptPreviewPage })))
export const TeleprompterPage = lazy(() => import('@/features/teleprompter/pages/teleprompter-page').then(({ TeleprompterPage }) => ({ default: TeleprompterPage })))
export const DebyPage = lazy(() => import('@/features/deby/pages/deby-page').then(({ DebyPage }) => ({ default: DebyPage })))
export const CalendarPage = lazy(() => import('@/features/calendar/pages/calendar-page').then(({ CalendarPage }) => ({ default: CalendarPage })))
export const MaterialsPage = lazy(() => import('@/features/materials/pages/materials-page').then(({ MaterialsPage }) => ({ default: MaterialsPage })))
export const SettingsPage = lazy(() => import('@/features/settings/pages/settings-page').then(({ SettingsPage }) => ({ default: SettingsPage })))
export const CampaignsPage = lazy(() => import('@/features/campaigns/pages/campaigns-page').then(({ CampaignsPage }) => ({ default: CampaignsPage })))
export const ApprovalsPage = lazy(() => import('@/features/approvals/pages/approvals-page').then(({ ApprovalsPage }) => ({ default: ApprovalsPage })))
export const PublicApprovalPage = lazy(() => import('@/features/approvals/pages/public-approval-page').then(({ PublicApprovalPage }) => ({ default: PublicApprovalPage })))
export const PublicBatchApprovalPage = lazy(() => import('@/features/approvals/pages/public-batch-approval-page').then(({ PublicBatchApprovalPage }) => ({ default: PublicBatchApprovalPage })))
export const ReportsPage = lazy(() => import('@/features/reports/pages/reports-page').then(({ ReportsPage }) => ({ default: ReportsPage })))
